# Generated by Django 3.1.3 on 2020-11-09 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pushtokens', '0003_auto_20201109_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushmessage',
            name='custom_json_render',
        ),
    ]
