# Generated by Django 3.1.3 on 2020-11-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushtokens', '0005_pushmessage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushmessage',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
