# Generated by Django 3.1.3 on 2020-11-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushtokens', '0006_auto_20201109_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushmessage',
            name='last_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
